version:  '3.7'
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php
        restart: on-failure
        links:
            - mysql
        volumes:
            - './apps/backend:/apps/backend/'
        networks:
            - internal
    nginx:
        image: nginx:stable
        container_name: nginx
        restart: on-failure
        volumes:
            - './apps/backend/:/apps/backend/'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8089:80'
        depends_on:
            - php
        networks:
            - internal
    mysql:
        image: mysql:8.0.18
        container_name: mysql
        command: [
            '--default-authentication-plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'oleksii'
            MYSQL_PASS: '1'
            MYSQL_DATABASE: 'dictionary'
        volumes:
            - './docker/mysql/data:/var/lib/mysql'
        networks:
            - internal
    adminer:
        image: adminer:4.7.5
        container_name: adminer
        restart: on-failure
        environment:
            PMA_HOST: mysql
        ports:
            - '1594:8080'
        networks:
            - internal
networks:
    internal:
        driver: bridge